-- Uploads training recommender model lr-20261006-81ddfa and makes it the
-- active one. Generated by ml/train.py — do not edit by hand. Needs
-- migration 0040 applied first. Safe to re-run.
begin;

update public.training_ml_models set is_active = false where is_active;

insert into public.training_ml_models
    (version, trained_at, algorithm, features, means, scales, classes, coef, intercept, metrics, min_confidence, is_active)
values (
    'lr-20261006-81ddfa',
    '2026-10-06T04:24:38+00:00',
    'multinomial logistic regression (mean imputation + standardisation)',
    array['tenure_months', 'attendance_rate', 'punctuality_rate', 'risk_score', 'pe_technical', 'pe_behavioural', 'pe_leadership', 'trainings_completed', 'avg_training_score']::text[],
    array[28.54125, 94.72210570469798, 87.91115771812082, 84.66416666666667, 73.18447916666666, 71.98203125, 69.21448787061993, 2.1691666666666665, 75.81440953412785]::float8[],
    array[22.858732068311078, 3.819688306947877, 8.107813186588858, 20.657013723484386, 10.770892052950835, 9.741541418031273, 8.841826699245601, 2.140611121203994, 8.627650237907389]::float8[],
    array['technical', 'behavioural', 'leadership']::text[],
    array[[-0.5495960788131173, 0.28650646308342537, 0.21653939759892074, 0.4658286555425269, -1.6912193899903767, 0.8039154813171745, 0.43077298288435684, -0.03197107760660219, -0.431825903382558], [-0.13893786579792783, -0.5389943710101324, -0.4752693745378571, -1.1324545681194913, 0.7246764323345996, -1.302567070739148, 0.4227169145935251, 0.11532443754238382, 0.2904936711323858], [0.6885339446110462, 0.2524879079267059, 0.2587299769389378, 0.6666259125769578, 0.9665429576557772, 0.4986515894219732, -0.8534898974778825, -0.08335335993578499, 0.14133223225017214]]::float8[],
    array[0.0967440684989881, 0.16298776365784315, -0.2597318321568287]::float8[],
    '{"train_rows": 2400, "test_rows": 600, "test_accuracy": 0.7833, "test_macro_f1": 0.7765, "cv_accuracy": 0.7767, "baseline_accuracy": 0.5783, "coverage_at_threshold": 0.7467, "accuracy_at_threshold": 0.8594, "data": ["synthetic_employees.csv"]}'::jsonb,
    0.65,
    true
)
on conflict (version) do update set
    trained_at = excluded.trained_at, algorithm = excluded.algorithm,
    features = excluded.features, means = excluded.means, scales = excluded.scales,
    classes = excluded.classes, coef = excluded.coef, intercept = excluded.intercept,
    metrics = excluded.metrics, min_confidence = excluded.min_confidence, is_active = true;

-- Self-check: the database must reproduce the probabilities Python computed
-- for these sample employees, or the whole upload is rolled back.
do $$
declare
    v_id bigint;
    r jsonb;
begin
    select id into v_id from public.training_ml_models where version = 'lr-20261006-81ddfa';
    r := public.ml_score_features(v_id, '{"tenure_months": 36.0, "attendance_rate": 96.9, "punctuality_rate": 87.1, "risk_score": 84.0, "pe_technical": 83.0, "pe_behavioural": 62.1, "pe_leadership": 66.0, "trainings_completed": 2.0, "avg_training_score": 68.8}'::jsonb);
    if not (abs((r->'probabilities'->>'technical')::float8 - 0.01885450738055675) < 1e-6 and abs((r->'probabilities'->>'behavioural')::float8 - 0.6849965662296097) < 1e-6 and abs((r->'probabilities'->>'leadership')::float8 - 0.29614892638983364) < 1e-6) then
        raise exception 'Model check 1 failed: database scored %, expected {"technical": 0.01885450738055675, "behavioural": 0.6849965662296097, "leadership": 0.29614892638983364}', r->'probabilities';
    end if;
    r := public.ml_score_features(v_id, '{"tenure_months": 10.0, "attendance_rate": 98.0, "punctuality_rate": 81.6, "risk_score": 100.0, "pe_technical": 67.5, "pe_behavioural": 80.2, "pe_leadership": 74.2, "trainings_completed": 0.0, "avg_training_score": null}'::jsonb);
    if not (abs((r->'probabilities'->>'technical')::float8 - 0.9660397831203186) < 1e-6 and abs((r->'probabilities'->>'behavioural')::float8 - 0.00772164782770839) < 1e-6 and abs((r->'probabilities'->>'leadership')::float8 - 0.02623856905197308) < 1e-6) then
        raise exception 'Model check 2 failed: database scored %, expected {"technical": 0.9660397831203186, "behavioural": 0.00772164782770839, "leadership": 0.02623856905197308}', r->'probabilities';
    end if;
    r := public.ml_score_features(v_id, '{"tenure_months": 9.0, "attendance_rate": 93.1, "punctuality_rate": 85.6, "risk_score": 88.0, "pe_technical": 56.3, "pe_behavioural": 65.1, "pe_leadership": 50.1, "trainings_completed": 1.0, "avg_training_score": 71.7}'::jsonb);
    if not (abs((r->'probabilities'->>'technical')::float8 - 0.8865832933344153) < 1e-6 and abs((r->'probabilities'->>'behavioural')::float8 - 0.05948426659864978) < 1e-6 and abs((r->'probabilities'->>'leadership')::float8 - 0.05393244006693495) < 1e-6) then
        raise exception 'Model check 3 failed: database scored %, expected {"technical": 0.8865832933344153, "behavioural": 0.05948426659864978, "leadership": 0.05393244006693495}', r->'probabilities';
    end if;
    r := public.ml_score_features(v_id, '{"tenure_months": 8.0, "attendance_rate": 94.6, "punctuality_rate": 85.9, "risk_score": 100.0, "pe_technical": null, "pe_behavioural": null, "pe_leadership": null, "trainings_completed": 0.0, "avg_training_score": null}'::jsonb);
    if not (abs((r->'probabilities'->>'technical')::float8 - 0.6598198678171936) < 1e-6 and abs((r->'probabilities'->>'behavioural')::float8 - 0.15623301552621768) < 1e-6 and abs((r->'probabilities'->>'leadership')::float8 - 0.18394711665658878) < 1e-6) then
        raise exception 'Model check 4 failed: database scored %, expected {"technical": 0.6598198678171936, "behavioural": 0.15623301552621768, "leadership": 0.18394711665658878}', r->'probabilities';
    end if;
    r := public.ml_score_features(v_id, '{"tenure_months": 0.0, "attendance_rate": null, "punctuality_rate": null, "risk_score": 84.0, "pe_technical": null, "pe_behavioural": null, "pe_leadership": null, "trainings_completed": 0.0, "avg_training_score": null}'::jsonb);
    if not (abs((r->'probabilities'->>'technical')::float8 - 0.5759110745283513) < 1e-6 and abs((r->'probabilities'->>'behavioural')::float8 - 0.3341465944733427) < 1e-6 and abs((r->'probabilities'->>'leadership')::float8 - 0.08994233099830586) < 1e-6) then
        raise exception 'Model check 5 failed: database scored %, expected {"technical": 0.5759110745283513, "behavioural": 0.3341465944733427, "leadership": 0.08994233099830586}', r->'probabilities';
    end if;
    raise notice 'Model lr-20261006-81ddfa uploaded and verified.';
end;
$$;

commit;
